import Link from "next/link";

export const metadata = {
  title: {
    default: "Next.js by Amrit",
    template: "%s | Amrit",
  },
  description: "Generated by Amrit",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
      <nav>
        <div style={{ display: "flex" }}>
          <ul>
            <li>
              <Link href={"/docs"}>docs</Link>
            </li>
            <li>
              <Link href="/dashboard">dashboard</Link>
            </li>
            <li>
              <Link href="/register">register</Link>
            </li>
          </ul>
        </div>
      </nav>
      <input placeholder="Enter name" />
      {children}
      </body>
    </html>
  );
}
