export const metadata = {
  title: 'Next.js by Amrit',
  description: 'Generated by Amrit',
}

export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
