export const metadata = {
  title: {
    default: "Next.js by Amrit",
    template: "%s | Amrit",
  },
  description: "Generated by Amrit",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
