export const metadata = {
  title: "Dashboard",
  description: "Generated by Next",
};

export default function DashboardLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div>
          <nav>
            <ul>
              <li>Hello</li>
              <li>Hello</li>
              <li>Hello</li>
            </ul>
          </nav>
        </div>
        {children}
        <footer>
          <p>footer</p>
        </footer>
      </body>
    </html>
  );
}
